[package]
name = "gitea-timings"
version = "0.1.0"
authors = ["DuckDuckWhale"]
edition = "2018"

[profile.release]
codegen-units = 1
lto = true

[dependencies]
chrono = "0.4.19"
serde = "1.0.117"
unicode-width = "0.1.8"
ureq = { version = "1.5.2", features = ["json"] }
